name: takeaway_app
description: A takeaway simulation app for modeling and simulation project
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  device_preview: 1.2.0
  fl_chart: ^0.68.0
  flutter:
    sdk: flutter
  provider: ^6.1.1
  excel: ^4.0.6                        # 👈 إضافة الحزمة دي
  path_provider: ^2.1.5               # 👈 إضافة الحزمة دي
  share_plus: ^10.1.4            # 👈 إضافة الحزمة دي (لمشاركة الملف)
  open_file: ^3.5.11   
  permission_handler: ^11.3.1                   # 👈 إضافة الحزمة دي (لفتح الملف)

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/restaurant.jpg
