name: takeaway_app
description: A takeaway simulation app for modeling and simulation project
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  device_preview: 1.2.0
  fl_chart: ^0.68.0
  flutter:
    sdk: flutter
  provider: ^6.1.1

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/restaurant.jpg
